Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pts=np.array(pos[0:-2]) # take all points except last 2
calibration_bar_ends=np.array(pos[-2:]) # take only last 2 points
calibration_bar_length=100 #feet
scale=calibration_bar_length/np.abs(calibration_bar_ends[0,0]-calibration_bar_ends[1,0])  #feet/pixel

plt.close(fig='all')
pts=np.append(pts,[pts[0]], axis=0) # making a copy of the first point and adding to our list to close our polygon when plotting
vert_pos=[[0,i+1,i+2] for i in np.arange(len(pts)-3)]
tri_data=[pts[vertices] for vertices in vert_pos]

fig1, ax2 = plt.subplots(nrows=1, ncols=1, figsize=(8, 6))
img=mpimg.imread('../images/3114_06_smith_creek.png')
ax2.imshow(img) 
ax2.plot(pts[:,0],pts[:,1], 'ko-')
[ax2.text(*pts[i]+10,str(i)) for i in np.arange(len(pts)-1)]
#[ax2.plot(tri_data[i][:,0], tri_data[i][:,1], '-') for i in np.arange(len(tri_data))]
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      2[0m calibration_bar_ends[38;5;241m=[39mnp[38;5;241m.[39marray(pos[[38;5;241m-[39m[38;5;241m2[39m:]) [38;5;66;03m# take only last 2 points[39;00m
[0;32m      3[0m calibration_bar_length[38;5;241m=[39m[38;5;241m100[39m [38;5;66;03m#feet[39;00m
[1;32m----> 4[0m scale[38;5;241m=[39mcalibration_bar_length[38;5;241m/[39mnp[38;5;241m.[39mabs([43mcalibration_bar_ends[49m[43m[[49m[38;5;241;43m0[39;49m[43m,[49m[38;5;241;43m0[39;49m[43m][49m[38;5;241m-[39mcalibration_bar_ends[[38;5;241m1[39m,[38;5;241m0[39m])  [38;5;66;03m#feet/pixel[39;00m
[0;32m      6[0m plt[38;5;241m.[39mclose(fig[38;5;241m=[39m[38;5;124m'[39m[38;5;124mall[39m[38;5;124m'[39m)
[0;32m      7[0m pts[38;5;241m=[39mnp[38;5;241m.[39mappend(pts,[pts[[38;5;241m0[39m]], axis[38;5;241m=[39m[38;5;241m0[39m) [38;5;66;03m# making a copy of the first point and adding to our list to close our polygon when plotting[39;00m

[1;31mIndexError[0m: too many indices for array: array is 1-dimensional, but 2 were indexed
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

