Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Marker labelling
# cv2.connectedComponents(). labels background of the image with 0, 
#then other objects are labelled with integers starting from 1.
ret, markers = cv.connectedComponents(sure_fg)

plt.imshow(sure_fg[100:120, 0:20], cmap="gray");
pd.DataFrame(markers).iloc[100:120, 0:20]
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# Marker labelling[39;00m
[0;32m      2[0m [38;5;66;03m# cv2.connectedComponents(). labels background of the image with 0, [39;00m
[0;32m      3[0m [38;5;66;03m#then other objects are labelled with integers starting from 1.[39;00m
[1;32m----> 4[0m ret, markers [38;5;241m=[39m cv[38;5;241m.[39mconnectedComponents([43msure_fg[49m)
[0;32m      6[0m plt[38;5;241m.[39mimshow(sure_fg[[38;5;241m100[39m:[38;5;241m120[39m, [38;5;241m0[39m:[38;5;241m20[39m], cmap[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgray[39m[38;5;124m"[39m);
[0;32m      7[0m pd[38;5;241m.[39mDataFrame(markers)[38;5;241m.[39miloc[[38;5;241m100[39m:[38;5;241m120[39m, [38;5;241m0[39m:[38;5;241m20[39m]

[1;31mNameError[0m: name 'sure_fg' is not defined
NameError: name 'sure_fg' is not defined

