Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data=np.array(pos)
fig.canvas.mpl_disconnect(cid) #cid is the image above.  we need to close it first. 
fig, ax = plt.subplots()
ax.plot(data[:,0],data[:,1], 'bo-') #blue circles & lines
ax.set_aspect(1) # change this and see what it does
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      2[0m fig[38;5;241m.[39mcanvas[38;5;241m.[39mmpl_disconnect(cid) [38;5;66;03m#cid is the image above.  we need to close it first. [39;00m
[0;32m      3[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m----> 4[0m ax[38;5;241m.[39mplot([43mdata[49m[43m[[49m[43m:[49m[43m,[49m[38;5;241;43m0[39;49m[43m][49m,data[:,[38;5;241m1[39m], [38;5;124m'[39m[38;5;124mbo-[39m[38;5;124m'[39m) [38;5;66;03m#blue circles & lines[39;00m
[0;32m      5[0m ax[38;5;241m.[39mset_aspect([38;5;241m1[39m) [38;5;66;03m# change this and see what it does[39;00m
[0;32m      6[0m plt[38;5;241m.[39mshow()

[1;31mIndexError[0m: too many indices for array: array is 1-dimensional, but 2 were indexed
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

