Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.plot(logÏƒ, func(logÏƒ, *fit_vals), 'b--')
plt.plot(logÏƒ, lmparam, 'ro');
plt.xlabel('log(Ïƒ), log(MPa)')
plt.ylabel(f'LM = T*({out.x[0]:3.3f}+log($t_r$), KÂ·log(hrs)')
plt.title(f'C = {out.x[0]:3.3f}')
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [15][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m plt[38;5;241m.[39mplot(logÏƒ, [43mfunc[49m(logÏƒ, [38;5;241m*[39mfit_vals), [38;5;124m'[39m[38;5;124mb--[39m[38;5;124m'[39m)
[0;32m      2[0m plt[38;5;241m.[39mplot(logÏƒ, lmparam, [38;5;124m'[39m[38;5;124mro[39m[38;5;124m'[39m);
[0;32m      3[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mlog(Ïƒ), log(MPa)[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'func' is not defined
NameError: name 'func' is not defined

