Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy.optimize import curve_fit
#define a function for the fit.  In this case just a line
def lin(x, m, b):
    return m*x+b

best_vals, covar = curve_fit(lin, sch_slice['num faculty'], sch_slice['credit_faculty'])
print(f'Our fit is given by {best_vals[0]:.2f} x + {best_vals[1]:.2f}')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [16][0m, in [0;36m<cell line: 6>[1;34m()[0m
[0;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21mlin[39m(x, m, b):
[0;32m      4[0m     [38;5;28;01mreturn[39;00m m[38;5;241m*[39mx[38;5;241m+[39mb
[1;32m----> 6[0m best_vals, covar [38;5;241m=[39m curve_fit(lin, [43msch_slice[49m[[38;5;124m'[39m[38;5;124mnum faculty[39m[38;5;124m'[39m], sch_slice[[38;5;124m'[39m[38;5;124mcredit_faculty[39m[38;5;124m'[39m])
[0;32m      7[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mOur fit is given by [39m[38;5;132;01m{[39;00mbest_vals[[38;5;241m0[39m][38;5;132;01m:[39;00m[38;5;124m.2f[39m[38;5;132;01m}[39;00m[38;5;124m x + [39m[38;5;132;01m{[39;00mbest_vals[[38;5;241m1[39m][38;5;132;01m:[39;00m[38;5;124m.2f[39m[38;5;132;01m}[39;00m[38;5;124m'[39m)

[1;31mNameError[0m: name 'sch_slice' is not defined
NameError: name 'sch_slice' is not defined

