Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = r'C:\Users\sgc\Google Drive\Teaching\2114 & 3114 Math I & II\git_2114_3114\data for practice\plastic-cable-insulation-thickness\insulation1.csv' 
raw_data=pd.read_csv(path, low_memory=False) # read data in to a dataframe called 'raw_data'
df=raw_data.copy() # make a copy called 'df' to manipulate
slice=df.loc[:,'ExtrTemp':'Measure'] # let's take the 4 numeric columns and call it slice. These have the wrong data type.  Currently 'object' should be 'float64'
df.loc[:,'ExtrTemp':'Measure']=slice.apply(pd.to_numeric, errors='coerce') # fix these 4 columns to have type 'float64' and change all non-numeric entries to 'NaN'
df.loc[:,'Date']=pd.to_datetime(df.loc[:,'Date'], errors='coerce', infer_datetime_format=True) # change 'Date' column from 'object' datatype to 'datatime' datatype
toremove=df.isnull().any(axis=1) # find all rows that have at least one 'NaN' entry
df=df[~toremove] # take all rows that are not '~' one of the rows found above and replace the original dataframe 'df'

#let's plot the measured thickness vs the linespeed
xdata=df.loc[:,'LineSpeed']
ydata=df.loc[:,'Measure']
plt.plot(xdata, ydata, 'k.') # use black 'k' small points '.' versus larger dots 'o'
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_12252/1075523533.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [0mpath[0m [1;33m=[0m [1;34mr'C:\Users\sgc\Google Drive\Teaching\2114 & 3114 Math I & II\git_2114_3114\data for practice\plastic-cable-insulation-thickness\insulation1.csv'[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mraw_data[0m[1;33m=[0m[0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[0mpath[0m[1;33m,[0m [0mlow_memory[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m [1;31m# read data in to a dataframe called 'raw_data'[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0mdf[0m[1;33m=[0m[0mraw_data[0m[1;33m.[0m[0mcopy[0m[1;33m([0m[1;33m)[0m [1;31m# make a copy called 'df' to manipulate[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mslice[0m[1;33m=[0m[0mdf[0m[1;33m.[0m[0mloc[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;34m'ExtrTemp'[0m[1;33m:[0m[1;34m'Measure'[0m[1;33m][0m [1;31m# let's take the 4 numeric columns and call it slice. These have the wrong data type.  Currently 'object' should be 'float64'[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0mdf[0m[1;33m.[0m[0mloc[0m[1;33m[[0m[1;33m:[0m[1;33m,[0m[1;34m'ExtrTemp'[0m[1;33m:[0m[1;34m'Measure'[0m[1;33m][0m[1;33m=[0m[0mslice[0m[1;33m.[0m[0mapply[0m[1;33m([0m[0mpd[0m[1;33m.[0m[0mto_numeric[0m[1;33m,[0m [0merrors[0m[1;33m=[0m[1;34m'coerce'[0m[1;33m)[0m [1;31m# fix these 4 columns to have type 'float64' and change all non-numeric entries to 'NaN'[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    309[0m                     [0mstacklevel[0m[1;33m=[0m[0mstacklevel[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    310[0m                 )
[1;32m--> 311[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    312[0m [1;33m[0m[0m
[0;32m    313[0m         [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[0;32m    584[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    585[0m [1;33m[0m[0m
[1;32m--> 586[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    587[0m [1;33m[0m[0m
[0;32m    588[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    480[0m [1;33m[0m[0m
[0;32m    481[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 482[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    483[0m [1;33m[0m[0m
[0;32m    484[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m    809[0m             [0mself[0m[1;33m.[0m[0moptions[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m [1;33m=[0m [0mkwds[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    810[0m [1;33m[0m[0m
[1;32m--> 811[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    812[0m [1;33m[0m[0m
[0;32m    813[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_make_engine[1;34m(self, engine)[0m
[0;32m   1038[0m             )
[0;32m   1039[0m         [1;31m# error: Too many arguments for "ParserBase"[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1040[1;33m         [1;32mreturn[0m [0mmapping[0m[1;33m[[0m[0mengine[0m[1;33m][0m[1;33m([0m[0mself[0m[1;33m.[0m[0mf[0m[1;33m,[0m [1;33m**[0m[0mself[0m[1;33m.[0m[0moptions[0m[1;33m)[0m  [1;31m# type: ignore[call-arg][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1041[0m [1;33m[0m[0m
[0;32m   1042[0m     [1;32mdef[0m [0m_failover_to_python[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py[0m in [0;36m__init__[1;34m(self, src, **kwds)[0m
[0;32m     49[0m [1;33m[0m[0m
[0;32m     50[0m         [1;31m# open handles[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 51[1;33m         [0mself[0m[1;33m.[0m[0m_open_handles[0m[1;33m([0m[0msrc[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     52[0m         [1;32massert[0m [0mself[0m[1;33m.[0m[0mhandles[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m     53[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py[0m in [0;36m_open_handles[1;34m(self, src, kwds)[0m
[0;32m    220[0m         [0mLet[0m [0mthe[0m [0mreaders[0m [0mopen[0m [0mIOHandles[0m [0mafter[0m [0mthey[0m [0mare[0m [0mdone[0m [1;32mwith[0m [0mtheir[0m [0mpotential[0m [0mraises[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m    221[0m         """
[1;32m--> 222[1;33m         self.handles = get_handle(
[0m[0;32m    223[0m             [0msrc[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    224[0m             [1;34m"r"[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\common.py[0m in [0;36mget_handle[1;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[0;32m    699[0m         [1;32mif[0m [0mioargs[0m[1;33m.[0m[0mencoding[0m [1;32mand[0m [1;34m"b"[0m [1;32mnot[0m [1;32min[0m [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    700[0m             [1;31m# Encoding[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 701[1;33m             handle = open(
[0m[0;32m    702[0m                 [0mhandle[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    703[0m                 [0mioargs[0m[1;33m.[0m[0mmode[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\git_2114_3114\\data for practice\\plastic-cable-insulation-thickness\\insulation1.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sgc\\Google Drive\\Teaching\\2114 & 3114 Math I & II\\git_2114_3114\\data for practice\\plastic-cable-insulation-thickness\\insulation1.csv'

