Traceback (most recent call last):
  File "C:\Users\Sean\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Sean\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Sean\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def g(x, A, Î¼, Ïƒ):
    return A/(Ïƒ*np.sqrt(2*np.pi)) * np.exp(-1/2*((x - Î¼) / Ïƒ)**2)

model = Model(g) # g is the function we defined above
# now we help the fitting process by giving starting values and bounds on our parameters
params = Parameters()
# parameters given as: (NAME, VALUE, VARY?, MIN,  MAX,  EXPR,  BRUTE_STEP)
params.add_many(('A', 1, True, None, None, None, None),
                ('Î¼', 200, True, None, None, None, None),
                ('Ïƒ', 100, True, None, None, None, None))

# fix these lines below for your data set
x = "p1 cal x data"
y = "p1 cal y data"


result_p1 = model.fit(y, params, x=x) #now we perform the fit to our x & y data with the given params

plt.plot(x, y, 'b.') #our x,y data blue dots
plt.plot(x, result_p1.best_fit, 'r.', label='best fit') # our overall fit red line
plt.legend(loc='best')
plt.show()

#print(result.fit_report())
print(result.best_values)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Input [1;32mIn [13][0m, in [0;36m<cell line: 17>[1;34m()[0m
[0;32m     13[0m x [38;5;241m=[39m [38;5;124m"[39m[38;5;124mp1 cal x data[39m[38;5;124m"[39m
[0;32m     14[0m y [38;5;241m=[39m [38;5;124m"[39m[38;5;124mp1 cal y data[39m[38;5;124m"[39m
[1;32m---> 17[0m result_p1 [38;5;241m=[39m [43mmodel[49m[38;5;241;43m.[39;49m[43mfit[49m[43m([49m[43my[49m[43m,[49m[43m [49m[43mparams[49m[43m,[49m[43m [49m[43mx[49m[38;5;241;43m=[39;49m[43mx[49m[43m)[49m [38;5;66;03m#now we perform the fit to our x & y data with the given params[39;00m
[0;32m     19[0m plt[38;5;241m.[39mplot(x, y, [38;5;124m'[39m[38;5;124mb.[39m[38;5;124m'[39m) [38;5;66;03m#our x,y data blue dots[39;00m
[0;32m     20[0m plt[38;5;241m.[39mplot(x, result_p1[38;5;241m.[39mbest_fit, [38;5;124m'[39m[38;5;124mr.[39m[38;5;124m'[39m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mbest fit[39m[38;5;124m'[39m) [38;5;66;03m# our overall fit red line[39;00m

File [1;32m~\anaconda3\lib\site-packages\lmfit\model.py:1028[0m, in [0;36mModel.fit[1;34m(self, data, params, weights, method, iter_cb, scale_covar, verbose, fit_kws, nan_policy, calc_covar, max_nfev, **kwargs)[0m
[0;32m   1026[0m [38;5;66;03m# Make sure `dtype` for data is always `float64` or `complex128`[39;00m
[0;32m   1027[0m [38;5;28;01mif[39;00m np[38;5;241m.[39misrealobj(data):
[1;32m-> 1028[0m     data [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43masfarray[49m[43m([49m[43mdata[49m[43m)[49m
[0;32m   1029[0m [38;5;28;01melif[39;00m np[38;5;241m.[39miscomplexobj(data):
[0;32m   1030[0m     data [38;5;241m=[39m np[38;5;241m.[39masarray(data, dtype[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcomplex128[39m[38;5;124m'[39m)

File [1;32m<__array_function__ internals>:5[0m, in [0;36masfarray[1;34m(*args, **kwargs)[0m

File [1;32m~\anaconda3\lib\site-packages\numpy\lib\type_check.py:114[0m, in [0;36masfarray[1;34m(a, dtype)[0m
[0;32m    112[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m _nx[38;5;241m.[39missubdtype(dtype, _nx[38;5;241m.[39minexact):
[0;32m    113[0m     dtype [38;5;241m=[39m _nx[38;5;241m.[39mfloat_
[1;32m--> 114[0m [38;5;28;01mreturn[39;00m [43masarray[49m[43m([49m[43ma[49m[43m,[49m[43m [49m[43mdtype[49m[38;5;241;43m=[39;49m[43mdtype[49m[43m)[49m

[1;31mValueError[0m: could not convert string to float: 'p1 cal y data'
ValueError: could not convert string to float: 'p1 cal y data'

